import { ReactNode, FC } from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import MainLayout from "./layouts/MainLayout";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

interface IRootLayoutProps {
  children: ReactNode;
}

export const metadata: Metadata = {
  title: "Git Api Next App",
  description: "Generated by create next app",
};

const RootLayout: FC<IRootLayoutProps> = ({ children }) => (
  <html lang="en">
    <body className={inter.className}>
      <MainLayout>{children}</MainLayout>
    </body>
  </html>
);

export default RootLayout;
